### ISSUE TITLE
Dependencies' versions are not specified in requirements.txt

### ISSUE THREAD

**Issue by whalekeykeeper** [reubenharry/Recurrent-RSA#2]
Hi,
I am trying to reproduce this project.
I found all the dependencies' versions are not specified in the `requirements.txt`.

I am using `macOS Ventura 13.0`.
I have created a virtual environment for this project with Python interpreter version `3.6.15`.
However, I still can't find a way to install dependencies like `matplotlib` and `numpy`.

I have also tried to look up for the version of `matplotlib` which is compatible to python 3.6.15 (which is used in the virtual environment) and install that specific version directly. Sadly this idea didn't work.

I would like to ask you if any suggestions or if you could specify the version numbers (guess this might be difficult for a 5-year-ago project).

Thanks in advance. 
Will keep looking for solutions.

**Comment by reubenharry** [comment]
Hi,

Unfortunately, I don't remember the set up details since as you say it it quite old (and looking at it, a pretty messy codebase - sorry about that.). On the bright side, I'm guessing that if you install modern versions of numpy and matplotlib (which should be straightforward with pip or conda), then there shouldn't be too much of a problem getting the code running.

**Comment by whalekeykeeper** [comment]
Thanks for your quick reply.
I have fixed the problems by setting up a virtual environment and updated some out-of-date features in the code. 
Will go to explore more about the nature of the models.
Thanks again!
