### ISSUE TITLE
Can't find "charpragcap"

### ISSUE THREAD

**Issue by whalekeykeeper** [reubenharry/Recurrent-RSA#3]
Hi Reuben,
I couldn't find any package which has the name "charpragcap" and I feel it is a module that you wrote yourself.
It appeared in scripts like `build_data.py` and `generate_clusters.py` and so on in this repo. For example:
```
from charpragcap.utils.image_and_text_utils import (
    devectorize_caption,
    get_rep_from_id,
    split_dataset,
)
```
May I ask more details about it?

**Comment by whalekeykeeper** [comment]
I found it doesn't matter that much and I don't want to disturb you for a 5-year-ago project.

**Comment by reubenharry** [comment]
My suspicion is that it's from an old version of the library and was ported incorrectly. By the way, depending on what you're doing with this project, you might just find it easier to recode things from scratch using a more modern conditional language model. My recollection is that the code mainly does two things:

- implements a reweighting of the conditional language model's next word prediction (using the Rational Speech Acts model)
 implements a beam search, rather than greedily unrolling from the reweighted model.

I think the reason the code is such a mess is that I was experimenting with some more complex models, and didn't follow good coding practices at the same - sorry about that!
